apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app: flaresolverr
  namespace: arrsuite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          ports:
            - name: http
              containerPort: 8191
          env:
            - name: LOG_LEVEL
              value: "info" # Set the log level (debug, info, warn, error)
            - name: TZ
              value: "America/New_York" # Replace with your timezone
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  labels:
    app: flaresolverr
  namespace: arrsuite
spec:
  ports:
    - name: http
      port: 8191
      targetPort: 8191
  selector:
    app: flaresolverr
  type: LoadBalancer
