apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-pvc
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyseer
    app.kubernetes.io/instance: jellyseer
    app.kubernetes.io/name: jellyseer
  name: jellyseer
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer
        app.kubernetes.io/name: jellyseer
    spec:
      containers:
      - image: fallenbagel/jellyseerr
        imagePullPolicy: Always
        name: jellyseer
        resources:
          limits:
            memory: "768Mi"
            cpu: "0.5"
        ports:
        - containerPort: 5055
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: America/New_York
        volumeMounts:
        - mountPath: /app/config
          name: jellyseer
          subPath: config
      volumes:
        - name: jellyseer
          persistentVolumeClaim:
            claimName: jellyseer-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyseer
  name: jellyseer
  namespace: services 
spec:
  ports:
  - name: web-tcp
    port: 80
    protocol: TCP
    targetPort: 5055
  selector:
    app: jellyseer
  type: LoadBalancer  # Added to expose the service externally