apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-system
spec:
  type: LoadBalancer
  selector:
    app: rancher
  ports:
    - protocol: TCP
      name: http-tcp
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https-tcp
      port: 443
      targetPort: 443