apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: arrsuite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
  namespace: arrsuite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          ports:
            - name: http
              containerPort: 8989
          resources:
            limits:
              cpu: "0.75"
              memory: "500Mi"
          env:
            - name: TZ
              value: "America/New_York" # Replace with your timezone
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /mnt/tv
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: tv
          nfs:
            path: /mnt/user/Media/data/TV
            server: edc.alexandria.dc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
  namespace: arrsuite
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8989
  selector:
    app: sonarr
  type: LoadBalancer